// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Persistence;

#nullable disable

namespace Test.Persistence.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240227142114_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Test.Domain.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreInvoiceDetailId")
                        .HasColumnType("int");

                    b.Property<int>("PreInvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreInvoiceDetailId");

                    b.HasIndex("PreInvoiceHeaderId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreInvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreInvoiceHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("PreInvoiceDetails");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesLineId");

                    b.HasIndex("SellerId");

                    b.ToTable("PreInvoiceHeaders");
                });

            modelBuilder.Entity("Test.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4285),
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4320),
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4325),
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4329),
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4332),
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4337),
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4340),
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4344),
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4348),
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4353),
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4357),
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4359),
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4362),
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4410),
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4413),
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4416),
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4419),
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4423),
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4426),
                            Title = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4429),
                            Title = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4432),
                            Title = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4435),
                            Title = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4438),
                            Title = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4441),
                            Title = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4444),
                            Title = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4446),
                            Title = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4449),
                            Title = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4452),
                            Title = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4454),
                            Title = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4457),
                            Title = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4460),
                            Title = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4462),
                            Title = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4465),
                            Title = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4468),
                            Title = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4471),
                            Title = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4474),
                            Title = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4476),
                            Title = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4479),
                            Title = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4482),
                            Title = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4484),
                            Title = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4487),
                            Title = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4489),
                            Title = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4492),
                            Title = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4494),
                            Title = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4497),
                            Title = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4500),
                            Title = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4503),
                            Title = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4538),
                            Title = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4541),
                            Title = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4543),
                            Title = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4546),
                            Title = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4549),
                            Title = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4552),
                            Title = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4555),
                            Title = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4558),
                            Title = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4560),
                            Title = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4564),
                            Title = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4566),
                            Title = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4569),
                            Title = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4572),
                            Title = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4574),
                            Title = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4577),
                            Title = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4580),
                            Title = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4583),
                            Title = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4585),
                            Title = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4588),
                            Title = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4591),
                            Title = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4594),
                            Title = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4597),
                            Title = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4600),
                            Title = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4602),
                            Title = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4605),
                            Title = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4607),
                            Title = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4610),
                            Title = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4612),
                            Title = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4615),
                            Title = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4618),
                            Title = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4621),
                            Title = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4624),
                            Title = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4627),
                            Title = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4660),
                            Title = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4663),
                            Title = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4666),
                            Title = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4670),
                            Title = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4673),
                            Title = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4677),
                            Title = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4679),
                            Title = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4681),
                            Title = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4683),
                            Title = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4686),
                            Title = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4689),
                            Title = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4692),
                            Title = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4694),
                            Title = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4697),
                            Title = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4699),
                            Title = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4702),
                            Title = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4705),
                            Title = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4708),
                            Title = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4711),
                            Title = "Product 99"
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 2, 27, 17, 51, 14, 441, DateTimeKind.Local).AddTicks(4714),
                            Title = "Product 100"
                        });
                });

            modelBuilder.Entity("Test.Domain.ProductSaleLine", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SalesLineId");

                    b.HasIndex("SalesLineId");

                    b.ToTable("ProductSaleLines");
                });

            modelBuilder.Entity("Test.Domain.SalesLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SalesLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 3"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 4"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 5"
                        });
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesLineId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Test.Domain.Discount", b =>
                {
                    b.HasOne("Test.Domain.PreInvoiceDetail", "PreInvoiceDetail")
                        .WithMany()
                        .HasForeignKey("PreInvoiceDetailId");

                    b.HasOne("Test.Domain.PreInvoiceHeader", "PreInvoiceHeader")
                        .WithMany()
                        .HasForeignKey("PreInvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreInvoiceDetail");

                    b.Navigation("PreInvoiceHeader");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceDetail", b =>
                {
                    b.HasOne("Test.Domain.PreInvoiceHeader", "PreInvoiceHeader")
                        .WithMany("PreInvoiceDetails")
                        .HasForeignKey("PreInvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Product", "Product")
                        .WithMany("PreInvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreInvoiceHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.HasOne("Test.Domain.Customer", "Customer")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Seller", "Seller")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalesLine");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Test.Domain.ProductSaleLine", b =>
                {
                    b.HasOne("Test.Domain.Product", "Product")
                        .WithMany("ProductSaleLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany("ProductSaleLines")
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesLine");
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany()
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesLine");
                });

            modelBuilder.Entity("Test.Domain.Customer", b =>
                {
                    b.Navigation("PreInvoiceHeaders");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.Navigation("PreInvoiceDetails");
                });

            modelBuilder.Entity("Test.Domain.Product", b =>
                {
                    b.Navigation("PreInvoiceDetails");

                    b.Navigation("ProductSaleLines");
                });

            modelBuilder.Entity("Test.Domain.SalesLine", b =>
                {
                    b.Navigation("PreInvoiceHeaders");

                    b.Navigation("ProductSaleLines");
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.Navigation("PreInvoiceHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
