// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Persistence;

#nullable disable

namespace Test.Persistence.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Test.Domain.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreInvoiceDetailId")
                        .HasColumnType("int");

                    b.Property<int>("PreInvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreInvoiceDetailId");

                    b.HasIndex("PreInvoiceHeaderId");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreInvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreInvoiceHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("PreInvoiceDetails", (string)null);
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesLineId");

                    b.HasIndex("SellerId");

                    b.ToTable("PreInvoiceHeaders", (string)null);
                });

            modelBuilder.Entity("Test.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1575),
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1640),
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1646),
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1716),
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1721),
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1726),
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1730),
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1734),
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1738),
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1745),
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1748),
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1751),
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1755),
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1758),
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1761),
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1764),
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1768),
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1772),
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1775),
                            Title = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1779),
                            Title = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1783),
                            Title = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1787),
                            Title = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1791),
                            Title = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1794),
                            Title = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1797),
                            Title = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1800),
                            Title = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1804),
                            Title = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1807),
                            Title = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1810),
                            Title = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1814),
                            Title = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1818),
                            Title = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1822),
                            Title = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1825),
                            Title = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1829),
                            Title = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1832),
                            Title = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1835),
                            Title = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1857),
                            Title = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1860),
                            Title = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1864),
                            Title = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1867),
                            Title = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1871),
                            Title = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1874),
                            Title = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1877),
                            Title = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1880),
                            Title = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1884),
                            Title = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1887),
                            Title = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1890),
                            Title = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1894),
                            Title = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1897),
                            Title = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1900),
                            Title = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1902),
                            Title = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1906),
                            Title = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1909),
                            Title = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1912),
                            Title = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1916),
                            Title = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1919),
                            Title = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1922),
                            Title = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1925),
                            Title = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1928),
                            Title = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1932),
                            Title = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1935),
                            Title = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1938),
                            Title = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1942),
                            Title = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1945),
                            Title = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1948),
                            Title = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1953),
                            Title = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1956),
                            Title = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(1959),
                            Title = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2026),
                            Title = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2030),
                            Title = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2033),
                            Title = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2037),
                            Title = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2040),
                            Title = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2043),
                            Title = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2047),
                            Title = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2050),
                            Title = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2053),
                            Title = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2056),
                            Title = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2059),
                            Title = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2063),
                            Title = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2066),
                            Title = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2069),
                            Title = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2072),
                            Title = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2075),
                            Title = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2078),
                            Title = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2081),
                            Title = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2085),
                            Title = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2088),
                            Title = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2091),
                            Title = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2094),
                            Title = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2097),
                            Title = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2101),
                            Title = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2104),
                            Title = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2107),
                            Title = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2110),
                            Title = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2113),
                            Title = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2116),
                            Title = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2120),
                            Title = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2123),
                            Title = "Product 99"
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 632, DateTimeKind.Local).AddTicks(2127),
                            Title = "Product 100"
                        });
                });

            modelBuilder.Entity("Test.Domain.ProductSaleLine", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SalesLineId");

                    b.HasIndex("SalesLineId");

                    b.ToTable("ProductSaleLines", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 18,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 19,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 20,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 21,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 22,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 23,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 24,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 25,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 26,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 27,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 28,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 29,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 30,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 31,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 32,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 33,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 34,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 35,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 36,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 37,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 38,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 39,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 40,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 41,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 42,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 43,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 44,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 45,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 46,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 47,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 48,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 49,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 50,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 51,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 52,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 53,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 54,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 55,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 56,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 57,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 58,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 59,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 60,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 61,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 62,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 63,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 64,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 65,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 66,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 67,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 68,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 69,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 70,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 71,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 72,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 73,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 74,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 75,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 76,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 77,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 78,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 79,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 80,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 81,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 82,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 83,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 84,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 85,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 86,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 87,
                            SalesLineId = 1
                        },
                        new
                        {
                            ProductId = 88,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 89,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 90,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 91,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 92,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 93,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 94,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 95,
                            SalesLineId = 2
                        },
                        new
                        {
                            ProductId = 96,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 97,
                            SalesLineId = 3
                        },
                        new
                        {
                            ProductId = 98,
                            SalesLineId = 5
                        },
                        new
                        {
                            ProductId = 99,
                            SalesLineId = 4
                        },
                        new
                        {
                            ProductId = 100,
                            SalesLineId = 4
                        });
                });

            modelBuilder.Entity("Test.Domain.SalesLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SalesLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 3"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 4"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Line 5"
                        });
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalesLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesLineId");

                    b.ToTable("Sellers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1111),
                            FirstName = "FirstName 1",
                            LastName = "LastName 1",
                            SalesLineId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1133),
                            FirstName = "FirstName 2",
                            LastName = "LastName 2",
                            SalesLineId = 5
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1144),
                            FirstName = "FirstName 3",
                            LastName = "LastName 3",
                            SalesLineId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1150),
                            FirstName = "FirstName 4",
                            LastName = "LastName 4",
                            SalesLineId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1156),
                            FirstName = "FirstName 5",
                            LastName = "LastName 5",
                            SalesLineId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1163),
                            FirstName = "FirstName 6",
                            LastName = "LastName 6",
                            SalesLineId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1170),
                            FirstName = "FirstName 7",
                            LastName = "LastName 7",
                            SalesLineId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1176),
                            FirstName = "FirstName 8",
                            LastName = "LastName 8",
                            SalesLineId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1180),
                            FirstName = "FirstName 9",
                            LastName = "LastName 9",
                            SalesLineId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 27, 17, 52, 15, 633, DateTimeKind.Local).AddTicks(1188),
                            FirstName = "FirstName 10",
                            LastName = "LastName 10",
                            SalesLineId = 2
                        });
                });

            modelBuilder.Entity("Test.Domain.Discount", b =>
                {
                    b.HasOne("Test.Domain.PreInvoiceDetail", "PreInvoiceDetail")
                        .WithMany()
                        .HasForeignKey("PreInvoiceDetailId");

                    b.HasOne("Test.Domain.PreInvoiceHeader", "PreInvoiceHeader")
                        .WithMany()
                        .HasForeignKey("PreInvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreInvoiceDetail");

                    b.Navigation("PreInvoiceHeader");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceDetail", b =>
                {
                    b.HasOne("Test.Domain.PreInvoiceHeader", "PreInvoiceHeader")
                        .WithMany("PreInvoiceDetails")
                        .HasForeignKey("PreInvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Product", "Product")
                        .WithMany("PreInvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreInvoiceHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.HasOne("Test.Domain.Customer", "Customer")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Seller", "Seller")
                        .WithMany("PreInvoiceHeaders")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalesLine");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Test.Domain.ProductSaleLine", b =>
                {
                    b.HasOne("Test.Domain.Product", "Product")
                        .WithMany("ProductSaleLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany("ProductSaleLines")
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesLine");
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.HasOne("Test.Domain.SalesLine", "SalesLine")
                        .WithMany()
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesLine");
                });

            modelBuilder.Entity("Test.Domain.Customer", b =>
                {
                    b.Navigation("PreInvoiceHeaders");
                });

            modelBuilder.Entity("Test.Domain.PreInvoiceHeader", b =>
                {
                    b.Navigation("PreInvoiceDetails");
                });

            modelBuilder.Entity("Test.Domain.Product", b =>
                {
                    b.Navigation("PreInvoiceDetails");

                    b.Navigation("ProductSaleLines");
                });

            modelBuilder.Entity("Test.Domain.SalesLine", b =>
                {
                    b.Navigation("PreInvoiceHeaders");

                    b.Navigation("ProductSaleLines");
                });

            modelBuilder.Entity("Test.Domain.Seller", b =>
                {
                    b.Navigation("PreInvoiceHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
